spec:
  container:
  - name: vllm
    image: "<Snowflake acct>.registry.snowflakecomputing.com/mistral_vllm_db/public/images/mistral"
    volumeMounts:
      - name: stage
        mountPath: /workspace/stage
    env:
      LLM_MODEL: mistralai/Mistral-7B-Instruct-v0.1
      HUGGINGFACE_TOKEN: <you huggingface token>
      SNOW_ROLE: SYSADMIN
      SNOW_WAREHOUSE: BI_WH
      SNOW_DATABASE: mistral_vllm_db
      SNOW_SCHEMA: PUBLIC
      temperature: 0
      max_tokens: 200
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
  volume:
  - name: stage
    source: "@FILES"
    uid: 1000
    gid: 1000
  endpoint:
  - name: mistral
    port: 8000
    public: true
  - name: jupyter # For jupyter only - remove only validated
    port: 8888
    public: true
